version: '3'
services:
  poi:
    build:
      context: ../src/poi
      dockerfile: Dockerfile
    image: tripinsights/poi:${TAG}

  trips:
    build:
      context: ../src/trips
      dockerfile: Dockerfile
    image: tripinsights/trips:${TAG}
  
  user-java:
    build:
      context: ../src/user-java
      dockerfile: Dockerfile
    image: tripinsights/user-java:${TAG}
  
  userprofile:
    build:
      context: ../src/userprofile
      dockerfile: Dockerfile
    image: tripinsights/userprofile:${TAG}

  tripviewer:
    build:
      context: ../src/tripviewer
      dockerfile: Dockerfile
    image: tripinsights/tripviewer:${TAG}