version: '3'
services:
  poi:
    build:
      context: ../src/poi
      dockerfile: Dockerfile
    image: tripinsights/poi:${IMAGE_TAG}

  trips:
    build:
      context: ../src/trips
      dockerfile: Dockerfile
    image: tripinsights/trips:${IMAGE_TAG}
  
  user-java:
    build:
      context: ../src/user-java
      dockerfile: Dockerfile
    image: tripinsights/user-java:${IMAGE_TAG}
  
  userprofile:
    build:
      context: ../src/userprofile
      dockerfile: Dockerfile
    image: tripinsights/userprofile:${IMAGE_TAG}

  tripviewer:
    build:
      context: ../src/tripviewer
      dockerfile: Dockerfile
    image: tripinsights/tripviewer:${IMAGE_TAG}